spring:
  application:
    name: Toxic-Chat
  datasource:
    #    name: xMarket_Data
    #    platform: mysql
    #    url: jdbc:mysql://us-cdbr-east-03.cleardb.com:3306/heroku_3ed503f241cf319?reconnect=true
    #    username: b719f422f2686b
    #    password: 8f19507c
    name: heroku_5cdec0192cfaf15
    platform: mysql
    url: jdbc:mysql://us-cdbr-east-03.cleardb.com/heroku_5cdec0192cfaf15?reconnect=true
    username: ba83d12dc09e4a
    password: e3463386

    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connectionTestQuery: select 1
      maximum-pool-size: 2
      connection-timeout: 60000

logging:
  level:
    com:
      spring:
        ibatis:
          UserMapper=DEBUG:
mybatis:
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: classpath:/dao/*Dao.xml

server:
  error:
    include-message: always