spring:
  application:
    name: Toxic-Chat
  datasource:
    name: heroku_5cdec0192cfaf15
    platform: mysql
    url: jdbc:mysql://us-cdbr-east-03.cleardb.com/heroku_5cdec0192cfaf15?reconnect=true
    username: ba83d12dc09e4a
    password: e3463386
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connectionTestQuery: select 1
      maximum-pool-size: 2
      connection-timeout: 60000
#  security:
#    oauth2:
#      client:
#        registration:
#          auth0:
#            client-id: cM0YFOhYQW5M92CbBR5SlGHBIiwaaf4M
#            client-secret: K18O_YOq_x37_eOTpsWtIpkdC5uB4rFMyWKpsIoEthfK_9XY5nGESCV39xJ8vMEJ
#            scope:
#              - openid
#              - profile
#              - email
#        provider:
#          auth0:
#            # trailing slash is important!
#            issuer-uri: https://fulano-es.us.auth0.com/
logging:
  level:
    com:
      spring:
        ibatis:
          UserMapper=DEBUG:
mybatis:
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: classpath:/dao/*Dao.xml

server:
  error:
    include-message: always