###(local)
POST http://localhost:8080/entities
Accept: application/json
Content-Type: application/json

{
  "text": "Bendiciones a toda tu familia"
}

###(local)
POST http://localhost:8080/sentiment
Accept: application/json
Content-Type: application/json

{
  "text": "Bendiciones a toda tu familia"
}

###(heroku)
POST https://bakend-toxic-chat.herokuapp.com/entities
Accept: application/json
Content-Type: application/json

{
  "text": "Bendiciones a toda tu familia"
}

###(heroku)
POST https://bakend-toxic-chat.herokuapp.com/sentiment
Accept: application/json
Content-Type: application/json

{
  "text": "Bendiciones a toda tu familia"
}

###(heroku)
POST https://bakend-toxic-chat.herokuapp.com/keyphrases
Accept: application/json
Content-Type: application/json

{
  "text": "Bendiciones a toda tu familia"
}
