###
POST http://localhost:8080/toxic/chat/text
Content-Type: application/json

{
  "text": "gg el proyecto"
}

###(heroku)
POST https://bakend-toxic-chat.herokuapp.com/toxic/chat/text
Content-Type: application/json

{
  "text": "gg el proyecto"
}